version: '3.5'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    hostname: postgresnest
    networks:
      - dev-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB_PREFIX:-Db}${POSTGRES_DB_NAME:-postgres}
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB_SSLMODE: ${POSTGRES_DB_SSLMODE:-disable}
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - ./postgres-server_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-disable} ${POSTGRES_DB_NAME:-postgres}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    networks:
      - dev-network
    ports:
      - "8200:8978"
    volumes:
      - ./cloudbeaver-data:/opt/cloudbeaver/workspace
  run-server:
    container_name: "nest-api_${NODE_ENV}"
    environment:
      - NODE_ENV:${NODE_ENV}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_DB:${POSTGRES_DB_NAME}
    build:
      context: ./
      target: run-server
      dockerfile: Dockerfile-windows
    networks:
      - dev-network
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - postgres
    restart: unless-stopped
  run-client:
    container_name: "c8-48_client_${NODE_ENV}"
    environment:
      - NODE_ENV:${NODE_ENV}
      - REACT_APP_API_URL:${REACT_APP_API_URL}
    env_file:
      - .env
    build:
      context: ./
      target: run-client
      dockerfile: Dockerfile-windows
    ports:
      - 8080:8080
    networks:
      - dev-network
    depends_on:
      - run-server
    command: yarn dev --host --port 8080
    restart: unless-stopped
networks:
  dev-network:
    ipam:
      config:
        - subnet: 172.33.0.0/16
  services:
    name: ${DATABASE_NETWORK:-nest-network}
  default:
    ipam:
      config:
        - subnet: 172.32.0.0/18
volumes:
  postgres-server_data:
    driver: local
    name: postgres-server_data
  cloudbeaver-data:
    driver: local
    name: cloudbeaver-data
