version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    networks:
      - nesjs-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: "${POSTGRES_DB_PREFIX}_${POSTGRES_DB_NAME}"
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - ./pgdata/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - nesjs-network
  server-production:
    build:
      context: ./
      target: server-production
    ports:
      - 8080:3000
    environment:
      NODE_ENV: production
  run-server:
    build:
      context: ./
      target: run-server
    ports:
      - 8080:3000
    command: yarn start:dev
    volumes:
      - ./server:/server
networks:
  services:
    name: ${DATABASE_NETWORK:-c8-48}
  default:
    ipam:
      config:
      - subnet: 172.32.0.0/18
