version: '3.5'
services:
  server-production:
    build:
      context: ./
      target: server-production
    ports:
      - 8080:3000
    environment:
      NODE_ENV: production
  run-server:
    build:
      context: ./
      target: run-server
    ports:
      - 8080:3000
    command: yarn start:dev
    volumes:
      - ./server:/server
networks:
  services:
    name: ${DATABASE_NETWORK:-c8-48}
  default:
    ipam:
      config:
      - subnet: 172.32.0.0/18
