name: Deploy Website

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: |
            ./server/yarn.lock
            ./client/yarn.lock

      - name: Install package - client
        working-directory: ./client
        run: yarn install --frozen-lockfile
      - name: build - client
        working-directory: ./client
        env:
          NODE_ENV: production
        run: yarn build
      - run: npm install -g surge
      - run: surge ./client/dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
