---
name: Lint Code Base
on:
  push:
    branches: [dev, main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, dev, release-*]
  workflow_dispatch:

jobs:
  server:
    name: Lint Code Base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: |
            ./server/yarn.lock
            ./client/yarn.lock

      - name: Install package - server
        working-directory: ./server
        run: yarn install --frozen-lockfile
      - name: spelling - server
        working-directory: ./server
        run: yarn spelling
      - name: eslint - server
        working-directory: ./server
        run: yarn lint
      - name: prettier - server
        working-directory: ./server
        run: yarn format
      - name: test - server
        working-directory: ./server
        run: yarn test
      - name: build - server
        working-directory: ./server
        env:
          NODE_ENV: production
        run: yarn build
        with:
          switches: -avzr --delete
          path: ./server/dist
          remote_path: /var/www/my-app/
          remote_host: ec2-54-80-18-152.compute-1.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Install package - client
        working-directory: ./client
        run: yarn install --frozen-lockfile
      - name: eslint - client
        working-directory: ./client
        run: yarn lint
      - name: prettier - client
        working-directory: ./client
        run: yarn format
      - name: spelling - client
        working-directory: ./client
        run: yarn spelling
      - name: build - client
        working-directory: ./client
        env:
          NODE_ENV: production
        run: yarn build
    env:
      CI: true
